[theme]
base                     = "light"
primaryColor             = "#CF2708"
backgroundColor          = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#111827"
font                     = "sans serif"
